# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
    # adapter: sqlite3
    # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    # timeout: 5000
    # database: db/development.sqlite3

    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV.fetch("MYSQL_USER") { "" } %>
    password: <%= ENV.fetch("MYSQL_PASSWORD")  { "" } %>
    host: <%= ENV.fetch("MYSQL_HOST") { "" }  %>
    database: <%= ENV.fetch("MYSQL_DBNAME") { "" }  %>

development:
   <<: *default

test:
  <<: *default
#  database: db/test.sqlite3

production:
  <<: *default
#  database: db/production.sqlite3
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD")  { "" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "" }  %>
  database: <%= ENV.fetch("MYSQL_DBNAME") { "" }  %>
